# Generated by Django 2.0.7 on 2018-11-30 05:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bouncer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('6d462c7a-7e9e-4a8c-a3bc-8d6445156809'))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
