# Generated by Django 2.1.2 on 2018-12-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouncer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='9d06f662-e06b-45c6-a81a-9364c81e8d38', editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
