# Generated by Django 2.0.7 on 2018-11-30 05:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bouncer', '0002_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('d13a3211-2358-4a13-b515-23a4f022ea63')),
        ),
    ]
