# Generated by Django 2.0.7 on 2018-11-30 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bouncer', '0003_auto_20181130_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(auto_created=uuid.UUID('e834f682-efc6-4f29-9595-457c0ac864fd'), max_length=50, primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('110487a6-2a5d-452a-b3f9-e32ba372df7c')),
        ),
    ]
