# Generated by Django 2.0.7 on 2018-11-30 06:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bouncer', '0004_auto_20181130_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='whizdom', max_length=256, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='card',
            name='body',
            field=models.TextField(default='whizdom', verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='card',
            name='headline',
            field=models.CharField(default='whizdom', max_length=256, verbose_name='Headline'),
        ),
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(default='whizdom', max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('f87876fe-e47f-4a07-b029-ac58b58aedb8')),
        ),
        migrations.AddField(
            model_name='media',
            name='card',
            field=models.ManyToManyField(to='bouncer.Card', verbose_name='Card'),
        ),
    ]
