# Generated by Django 2.0.7 on 2018-12-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouncer', '0004_auto_20181204_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='cde2725d-ca6f-49e8-898e-963204731c38', editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
