# Generated by Django 2.0.7 on 2018-11-30 06:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bouncer', '0005_auto_20181130_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('1d4465ef-3e85-4c27-8f46-dd6443ce3572')),
        ),
    ]
