# Generated by Django 2.0.7 on 2018-11-30 06:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bouncer', '0006_auto_20181130_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='video',
            field=models.TextField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('0a7d8245-dde5-465e-a1d5-2fa731fc5bf0')),
        ),
    ]
