# Generated by Django 2.0.7 on 2018-11-30 06:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bouncer', '0007_auto_20181130_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('018f321c-9e17-48db-850d-4347abbbcd47')),
        ),
    ]
