# Generated by Django 2.0.7 on 2018-11-30 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bouncer', '0008_auto_20181130_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('aac58589-3832-4d9d-aa9c-4a3fa2fbbda6')),
        ),
        migrations.AlterField(
            model_name='media',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
