# Generated by Django 2.1.2 on 2018-12-06 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='whizdom', max_length=256, verbose_name='Name')),
                ('body', models.TextField(default='whizdom', verbose_name='Body')),
                ('headline', models.CharField(default='whizdom', max_length=256, verbose_name='Headline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='whizdom', max_length=256, verbose_name='Name')),
                ('is_image', models.BooleanField(default=False, verbose_name='is_image')),
                ('is_video', models.BooleanField(default=False, verbose_name='is_video')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('video', models.TextField(blank=True, null=True, verbose_name='Video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='card',
            name='media',
            field=models.ManyToManyField(to='content.Media', verbose_name='Media'),
        ),
    ]
