# Generated by Django 2.1.2 on 2018-12-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default='aa1945d3-cb83-4b5d-a35d-439bf14309cf', editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='whizdom', max_length=256, verbose_name='Name')),
                ('body', models.TextField(default='whizdom', verbose_name='Body')),
                ('headline', models.CharField(default='whizdom', max_length=256, verbose_name='Headline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default='aa1945d3-cb83-4b5d-a35d-439bf14309cf', editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='whizdom', max_length=256, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('video', models.TextField(blank=True, null=True, verbose_name='Video')),
                ('card', models.ManyToManyField(to='content.Card', verbose_name='Card')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
