# Generated by Django 2.0.7 on 2018-12-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(default='9f9a058f-5dc2-4154-b2b4-9ae5b6bc9d60', editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='media',
            field=models.ManyToManyField(to='content.Media', verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.CharField(default='9f9a058f-5dc2-4154-b2b4-9ae5b6bc9d60', editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
