# Generated by Django 2.1.2 on 2018-12-03 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('0937d8e7-b8ac-4e69-9622-62dce5d4227c')),
        ),
    ]
