# Generated by Django 2.1.2 on 2018-12-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20181203_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(default='4c273a16-a63e-4240-971e-24719015db7f', editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.CharField(default='4c273a16-a63e-4240-971e-24719015db7f', editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
