# Generated by Django 2.0.7 on 2018-12-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20181204_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(default='5284c0b5-f8ef-4129-8c76-06ba3d4fb281', editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='media',
            field=models.ManyToManyField(blank=True, null=True, to='content.Media', verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.CharField(default='5284c0b5-f8ef-4129-8c76-06ba3d4fb281', editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
