# Generated by Django 2.1.2 on 2018-12-03 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20181203_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('21821829-d158-48a1-9adc-353ac6fa98df')),
        ),
    ]
