# Generated by Django 2.0.7 on 2018-12-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20181204_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_image',
            field=models.BooleanField(default=False, verbose_name='Image Checkbox'),
        ),
        migrations.AddField(
            model_name='media',
            name='is_video',
            field=models.BooleanField(default=False, verbose_name='Video Checkbox'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(default='32a6198d-21c3-41cb-9219-3278ff465ca4', editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.CharField(default='32a6198d-21c3-41cb-9219-3278ff465ca4', editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
