# Generated by Django 2.1.2 on 2018-12-03 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20181203_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('4775c9d4-d670-462a-877f-8c3b4b0b9f2e')),
        ),
    ]
