# Generated by Django 2.1.2 on 2018-12-03 07:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20181203_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('f7779fc4-2f9a-4b05-b183-462a9ff6e857')),
        ),
    ]
