# Generated by Django 2.0.7 on 2018-12-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20181204_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(default='cde2725d-ca6f-49e8-898e-963204731c38', editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='media',
            field=models.ManyToManyField(to='content.Media', verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.CharField(default='cde2725d-ca6f-49e8-898e-963204731c38', editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_image',
            field=models.BooleanField(default=False, verbose_name='is_image'),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_video',
            field=models.BooleanField(default=False, verbose_name='is_video'),
        ),
    ]
